env_name            = "sandbox"
remote_state_bucket = "tawkify-tfstate-sandbox"
remote_state_key    = "global/s3/terraform.tfstate"
cluster_region      = "us-west-2"
role_arn            = "arn:aws:iam::352587061287:role/Tawkify-dataeng-admin"