bucket         = "tawkify-kubeflow-tfstate-sandbox"
key            = "global/s3/terraform.tfstate"
region         = "us-west-2"
dynamodb_table = "tawkify-kubeflow-tfstate-sandbox"
role_name      = "Tawkify-dataeng-admin"
env_name       = "sandbox"
